### ISSUE TITLE
Easy ID on hydra IRC?

### ISSUE THREAD

**Issue by larsmartin4** [HydraIRC/hydrairc#18]
Microsoft and other did use 2 way login with sms or google authenticator or other its possible to make profile with that futures or link or easy way to logon on multi computer without need to login manualy?

Microsoft have ID same with google apps and other\ apple, but its not futures with this more that use email or other way to login?

**Comment by gdwnldsKSC** [comment]
Given that any authentication happening is to the IRC servers directly, this isn't something that would bring any value or usability improvements, especially since no IRC network to my knowledge uses this kind of authentication at all - it's either certificate based or password via SASL/connection parameters/nickserv commands. 

Potentially user profile synchronization could be added, but that can also be achieved just by copying the user profile files via your cloud sync of choice (dropbox, onedrive, etc....).

**Comment by hydra** [comment]
> Given that any authentication happening is to the IRC servers directly, this isn't something that would bring any value or usability improvements, especially since no IRC network to my knowledge uses this kind of authentication at all - it's either certificate based or password via SASL/connection parameters/nickserv commands.
> 
> Profiles on Hydra (and other IRC clients) are merely specifying the parameters of connection and what authentication parameters (if any) you are passing to the IRC server - or automatic actions taken after connection.

agreed, closing.
